version: "2"

services:
  clustercontrol:
    image: severalnines/clustercontrol
    ports:
      - "5000:80"
      - "5001:443"
      - "9443:9443"
      - "19501:19501"
    environment:
      DOCKER_HOST_ADDRESS: 192.168.11.111
      CMON_PASSWORD: DAakJ[t8-Zp=A3{&%K@CzgHY8&dH
      MYSQL_ROOT_PASSWORD: DAakJ[t8-Zp=A3{&%K@CzgHY8&dH
    volumes:
      - cc-cmond:/etc/cmon.d
      - cc-datadir:/var/lib/mysql
      - cc-ssh:/root/.ssh
      - cc-cmonlib:/var/lib/cmon
      - cc-backups:/root/backups
      - prom-data:/var/lib/prometheus
      - prom-conf:/etc/prometheus
volumes:
  cc-cmond:
  cc-datadir:
  cc-ssh:
  cc-cmonlib:
  cc-backups:
  prom-data:
  prom-conf:
